<table>
    <tr>
        <td><img src="./img/Macc.png" width="400"/></td>
        <td>&nbsp;</td>
        <td>
            <h1 style="color:blue;text-align:left">Álgebra Lineal</h1></td>
        <td>
            <table><tr>
            <tp><p style="font-size:150%;text-align:center">Sesión 4</p></tp>
            <tp><p style="font-size:150%;text-align:center">Eliminación usando matrices</p></tp>
            </tr></table>
        </td>
    </tr>
</table>

---

## Objetivos

1. Expresar los pasos del método de eliminación mediante matrices elementales $E$.
2. Conocer la fundamentación conceptual de la multiplicación entre matrices.
3. Realizar multiplicación entre matrices.

Adaptado de Strang (2009), capítulo 1, sección 2.3.


## Eliminación expresada mediante matrices

**Recorderis de la multiplicación entre una matriz y un vector**

En la sesión 3 vimos que un sistema de ecuaciones tiene una representación matricial $A\pmb{x}=\pmb{b}$. Para poder hacer esta representación, definimos la multiplicación entre la matriz de coeficientes $A$ y el vector incógnita $\pmb{x}$ mediante un método fila y mediante un método columna, ambos dando lugar al mismo resultado: el sistema de ecuaciones original.

Recordemos cómo funciona la multiplicación de una matriz por un vector mediante el siguiente ejemplo:

$$
\begin{bmatrix}
3 & 4\\  
5 & 6\\  
\end{bmatrix}\begin{bmatrix}
2\\  
1\\  
\end{bmatrix} = \begin{bmatrix}
3*2 + 4*1\\  
5*2 + 6*1\\  
\end{bmatrix} = \begin{bmatrix}
10\\  
16\\  
\end{bmatrix}
$$

De manera general, esta multiplicación procede así:

$$
\begin{bmatrix}
a_{11} & a_{12}\\  
a_{21} & a_{22}\\  
\end{bmatrix}\begin{bmatrix}
x_1\\  
x_2\\  
\end{bmatrix} = \begin{bmatrix}
a_{11}x_1 + a_{12}x_2\\  
a_{21}x_1 + a_{22}x_2\\  
\end{bmatrix}
$$

**Recorderis de la eliminación**

La operación básica de la eliminación es la sustración de múltipos de una ecuación de otra ecuación. En este ejemplo

$$
\begin{align*}
2x_1 + 4x_2 - 2x_3 &= 2\\  
4x_1 + 9x_2 - 3x_3 &= 8\\  
-2x_1 - 3x_2 + 7x_3 &= 10\\  
\end{align*}
$$

al sustraer 2 veces la primera fila de la segunda se obtiene:

$$
\begin{align*}
2x_1 + &4x_2 &- 2x_3 &= 2\\  
       &x_2 &+ x_3 &= 4\\  
-2x_1 - &3x_2 &+ 7x_3 &= 10\\  
\end{align*}
$$

**Forma matricial del sistema**

Este sistema se puede representar mediante matrices así:

$$
\begin{bmatrix}
2 & 4 & -2\\  
4 & 9 & -3\\  
-2 & -3 & 7\\  
\end{bmatrix}\begin{bmatrix}
x_1\\  
x_2\\
x_3
\end{bmatrix} = \begin{bmatrix}
2\\  
8\\
10
\end{bmatrix}
$$

## Matrices de eliminación

Ahora, respecto al lado derecho de la ecuación, podemos representar el paso de eliminación arriba consignado (sustraer dos veces la primera ecuación de la segunda) mediante la siguiente multiplicación de la matriz $E_{21}$ por el vector $\pmb{b}=(2, 8, 10)$:

$$
\begin{bmatrix}
1 & 0 & 0\\  
-2 & 1 & 0\\  
0 & 0 & 1\\  
\end{bmatrix}\begin{bmatrix}
2\\  
8\\
10
\end{bmatrix} = \begin{bmatrix}
2\\  
4\\
10
\end{bmatrix}
$$



**Ejercicio 1:**

* Compruebe este resultado mediante el método fila.
* Compruebe este resultado mediante la función `mult_fila`.

Observe que en general se tiene:

$$
\begin{bmatrix}
1 & 0 & 0\\  
-2 & 1 & 0\\  
0 & 0 & 1\\  
\end{bmatrix}\begin{bmatrix}
b_1\\  
b_2\\
b_3
\end{bmatrix} = \begin{bmatrix}
b_1\\  
-2b_1 + b_2\\
b_3
\end{bmatrix}
$$

**¿Cómo se obtiene $E_{21}$?**

Recordemos el sistema que estamos trabajando como ejemplo:

$$
\begin{align*}
2x_1 + 4x_2 - 2x_3 &= 2\\  
4x_1 + 9x_2 - 3x_3 &= 8\\  
-2x_1 - 3x_2 + 7x_3 &= 10\\  
\end{align*}
$$

También recuerde que uno de los pasos de la eliminación es encontrar el multiplicador $\ell_{21}$, que consiste en dividir el coeficiente de $x$ en la segunda fila, 4, por el pivot de la primera fila, 2, obteniendo $\ell_{21}=\frac{4}{2}=2$. 

Ahora, observe que la matriz de eliminación $E_{21}$ se obtiene al cambiar la posición $2,1$ de la matriz identidad por $-\ell_{21}$.

$$
I = \begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{bmatrix}\qquad E_{21}=\begin{bmatrix}
1 & 0 & 0\\
-2 & 1 & 0\\
0 & 0 & 1
\end{bmatrix} 
$$

**Ejercicio 2:**

Suponga que $\ell_{31}=4$ y que $\pmb{b}=\begin{bmatrix}
1\\ 3\\ 9\end{bmatrix}$. Encuentre:

* $E_{31}$
* $E_{31}\pmb{b}$

## Multiplicación de matrices

La idea de la representación matricial es expresar la operación elemental de eliminación mediante la multiplicación por matrices. En el lado derecho del sistema $A\pmb{x}=\pmb{b}$ hemos trabajado la multiplicación $E_{21}\pmb{b}$. Debemos también trabajar en el lado izquierdo la multiplicación $E_{21}A\pmb{x}$. Pero, ¿Cómo se define esta multiplicación?

Observe que debemos definir esta multiplicación de tal manera que:

1. $E_{21}(A\pmb{x})=(E_{21}A)\pmb{x}$. Es decir, que nos de lo mismo multiplicar $E_{21}$ por el resultado de la multiplicación de $A$ por el vector incógnita $\pmb{x}$ (es decir, esta última se realiza primero), a que primero multipliquemos las matrices $E_{21}$ y $A$, y luego este resultado se multiplique por el vector incógnita $\pmb{x}$.

2. La multiplicación $E_{21}A$ debe dar

$$
E_{21}A=\begin{bmatrix}
1 & 0 & 0\\
-2 & 1 & 0\\
0 & 0 & 1
\end{bmatrix}\begin{bmatrix}
2 & 4 & -2\\
4 & 9 & -3\\ 
-2 & -3 & 7
\end{bmatrix} = \begin{bmatrix}
2 & 4 & -2\\ 
0 & 1 & 1\\ 
-2 & -3 & 7\end{bmatrix}
$$

Toda vez que el resultado deseado de multiplicar por $E_{21}$ es restar dos veces la primera fila de la segunda.

La manera de definir esta multiplicación es como sigue:

$$
E_{21}A=E_{21}\begin{bmatrix}
\mbox{columna 1 de $A$} & \mbox{columna 2 de $A$} & \mbox{columna 3 de $A$}\end{bmatrix}
$$

$$
= \begin{bmatrix}
E_{21}(\mbox{columna 1 de $A$}) & E_{21}(\mbox{columna 2 de $A$}) & E_{21}(\mbox{columna 3 de $A$})\end{bmatrix}
$$

Es decir:

$$
E_{21}A= \begin{bmatrix}
E_{21}\begin{bmatrix}
2\\ 4\\ -2\end{bmatrix} & E_{21}\begin{bmatrix}
4\\ 9\\ -3\end{bmatrix} & E_{21}\begin{bmatrix}
-2\\ -3\\ 7\end{bmatrix}\end{bmatrix}
$$

Es decir:

$$
E_{21}A= \begin{bmatrix}
\begin{bmatrix}
1 & 0 & 0\\
-2 & 1 & 0\\
0 & 0 & 1
\end{bmatrix}\begin{bmatrix}
2\\ 4\\ -2\end{bmatrix} & \begin{bmatrix}
1 & 0 & 0\\
-2 & 1 & 0\\
0 & 0 & 1
\end{bmatrix}\begin{bmatrix}
4\\ 9\\ -3\end{bmatrix} & \begin{bmatrix}
1 & 0 & 0\\
-2 & 1 & 0\\
0 & 0 & 1
\end{bmatrix}\begin{bmatrix}
-2\\ -3\\ 7\end{bmatrix}\end{bmatrix}
$$



Verificar todas estas operaciones a mano se sale de mi zona de confort. Usemos más bien la función `mult_fila`:

In [31]:
E = np.matrix([[1,0,0], [-2,1,0],[0,0,1]])
A1 = np.array([2,4,-2])
A2 = np.array([4,9,-3])
A3 = np.array([-2,-3,7])
print(mult_fila(E,A1))
print(mult_fila(E,A2))
print(mult_fila(E,A3))

[ 2  0 -2]
[ 4  1 -3]
[-2  1  7]


Aquí no vemos bien la matriz, porque las columnas se ven como filas, pero el resultado está correcto. Hemos obtenido

$$
E_{21}A= \begin{bmatrix}
2 & 4 & -2\\ 
0 & 1 & 1\\ 
-2 & -3 & 7\end{bmatrix}
$$

## Matrices en numpy

Multiplicar matrices en numpy es muy fácil:

In [32]:
E = np.matrix([[1,0,0], [-2,1,0],[0,0,1]])
A = np.matrix([[2,4,-2], [4,9,-3], [-2,-3,7]])
E * A

matrix([[ 2,  4, -2],
        [ 0,  1,  1],
        [-2, -3,  7]])

Hemos dado una vuelta grande para llegar a la multiplicación de matrices, pero valió la pena, pues sabemos por qué las matrices se multiplican así.

Verifiquemos que la multiplicación de matrices es asociativa, pero no conmutativa en el siguiente ejercicio.

**Ejercicio 3:**

Sean $A=\begin{bmatrix}
1 & 2 & 3\\
3 & 1 & 2\\
0 & 2 & 1
\end{bmatrix}$, $B=\begin{bmatrix}
1 & 2 & -2\\
0 & 0 & 1\\
0 & -1 & 0
\end{bmatrix}$ y $C=\begin{bmatrix}
3 & 2 & 1\\
3 & 1 & 1\\
1 & 2 & 3
\end{bmatrix}$. Verifique que:

* $(AB)C=A(BC)$
* $AB\neq BA$

## Matrices de permutación

Considere el sistema:

$$
\begin{align*}
x + y + z &= 7\\  
x + y - z &= 5\\  
x - y + z &= 3\\  
\end{align*}
$$

Su forma matricial es:

$$
\begin{bmatrix}
1 & 1 & 1\\  
1 & 1 & -1\\  
1 & -1 & 1\\  
\end{bmatrix}\begin{bmatrix}
x\\  
y\\
z
\end{bmatrix} = \begin{bmatrix}
7\\  
5\\
3
\end{bmatrix}
$$

Para resolverlo, la primera eliminación que debemos hacer es sustraer la primera fila de la segunda. Hagamos esto mediante matrices. Necesitamos la matriz $E_{21}$ usando el multiplicador $\ell_{21}=1$. Debemos entonces encontrar las siguientes multiplicaciones de matrices:

$$
\begin{bmatrix}
1 & 0 & 0\\  
-1 & 1 & 0\\  
0 & 0 & 1\\  
\end{bmatrix}\begin{bmatrix}
1 & 1 & 1\\  
1 & 1 & -1\\  
1 & -1 & 1\\  
\end{bmatrix}\begin{bmatrix}
x\\  
y\\
z
\end{bmatrix} = \begin{bmatrix}
1 & 0 & 0\\  
-1 & 1 & 0\\  
0 & 0 & 1\\  
\end{bmatrix}\begin{bmatrix}
7\\  
5\\
3
\end{bmatrix}
$$

Obtenemos:

$$
\begin{bmatrix}
1 & 1 & 1\\  
0 & 0 & -2\\  
1 & -1 & 1\\  
\end{bmatrix}\begin{bmatrix}
x\\  
y\\
z
\end{bmatrix} = \begin{bmatrix}
7\\  
-2\\
3
\end{bmatrix}
$$

Ahora a eliminar la tercera ecuación, sustrayendo la primera de la tercera. Necesitamos la matriz $E_{31}$ usando el multiplicador $\ell_{31}=1$. Debemos entonces encontrar las siguientes multiplicaciones de matrices:

$$
\begin{bmatrix}
1 & 0 & 0\\  
0 & 1 & 0\\  
-1 & 0 & 1\\  
\end{bmatrix}\begin{bmatrix}
1 & 1 & 1\\  
0 & 0 & -2\\  
1 & -1 & 1\\  
\end{bmatrix}\begin{bmatrix}
x\\  
y\\
z
\end{bmatrix} = \begin{bmatrix}
1 & 0 & 0\\  
0 & 1 & 0\\  
-1 & 0 & 1\\  
\end{bmatrix}\begin{bmatrix}
7\\  
-2\\
3
\end{bmatrix}
$$

Obtenemos:

$$
\begin{bmatrix}
1 & 1 & 1\\  
0 & 0 & -2\\  
0 & -2 & 0\\  
\end{bmatrix}\begin{bmatrix}
x\\  
y\\
z
\end{bmatrix} = \begin{bmatrix}
7\\  
-2\\
-4
\end{bmatrix}
$$

Tenemos un problema. El pivote para las $y$s, que se encuentra en la posición 2, 2, es 0. Esto no es nada grave, pues podemos intercambiar la segunda y la tercera columna.

Hagamos esto mediante matrices. Podemos multiplicar a ambos lados por la matriz $P_{23}=\begin{bmatrix}
1 & 0 & 0\\  
0 & 0 & 1\\  
0 & 1 & 0\\  
\end{bmatrix}$:

$$
\begin{bmatrix}
1 & 0 & 0\\  
0 & 0 & 1\\  
0 & 1 & 0\\  
\end{bmatrix}\begin{bmatrix}
1 & 1 & 1\\  
0 & 0 & -2\\  
0 & -2 & 0\\  
\end{bmatrix}\begin{bmatrix}
x\\  
y\\
z
\end{bmatrix} = \begin{bmatrix}
1 & 0 & 0\\  
0 & 0 & 1\\  
0 & 1 & 0\\  
\end{bmatrix}\begin{bmatrix}
7\\  
-2\\
-4
\end{bmatrix}
$$

**Ejercicio 4:**

Verifique que las dos multiplicaciones anteriores tienen como resultado el intercambio de la segunda y tercera filas.

**Ejercicio 5:**

¿Qué número $d$ obliga un cambio de columna y cuál es el sistema triangular para este $d$? ¿Cuál $d$ hace que este sistema sea singular (sin solución)?

$$
\begin{align*}
2x + &5y + z &= 0\\  
4x + &dy + z &= 2\\  
&y - z &= 3
\end{align*}
$$

## La matriz aumentada

La representación matricial de un sistema de ecuaciones tiene la ventaja de obviar el uso de variables ($x$, $y$, etc.) para solo concentrarnos en los coeficientes. Existe una forma aún más conveniente de representar el sistema de ecuaciones, llamada la matriz aumentada.

Supongamos el siguiente sistema:

$$
\begin{align*}
2x_1 + 4x_2 - 2x_3 &= 2\\  
4x_1 + 9x_2 - 3x_3 &= 8\\  
-2x_1 - 3x_2 + 7x_3 &= 10\\  
\end{align*}
$$

La representación del sistema mediante la *matriz aumentada* consiste en incluir, en una sola matriz, tanto los coeficientes como las constantes al lado derecho de la igualdad:

$$
\begin{bmatrix}
A & \pmb{b}
\end{bmatrix} = \begin{bmatrix}
2 & 4 & -2 & 2\\  
4 & 9 & -3 & 8\\  
-2 & -3 & 7 & 10\\  
\end{bmatrix}
$$

De esta manera, podemos hacer una sola multiplicación por una matriz de eliminación (o de permutación) y no dos:

$$
E_{21}\begin{bmatrix}
A & \pmb{b}
\end{bmatrix} = \begin{bmatrix}
1 & 0 & 0\\
-2 & 1 & 0\\
0 & 0 & 1
\end{bmatrix}\begin{bmatrix}
2 & 4 & -2 & 2\\  
4 & 9 & -3 & 8\\  
-2 & -3 & 7 & 10\\  
\end{bmatrix}=\begin{bmatrix}
2 & 4 & -2 & 2\\  
0 & 1 & 1 & 4\\  
-2 & -3 & 7 & 10
\end{bmatrix}
$$

Confirmemos mediante numpy:

In [35]:
E = np.matrix([[1,0,0], [-2,1,0],[0,0,1]])
A = np.matrix([[2,4,-2,2], [4,9,-3,8], [-2,-3,7,10]])
E*A

matrix([[ 2,  4, -2,  2],
        [ 0,  1,  1,  4],
        [-2, -3,  7, 10]])

Esto funciona por la forma como hemos definido la multiplicación de matrices:

$$
E_{21}\begin{bmatrix}
A & \pmb{b}
\end{bmatrix} = \begin{bmatrix}
E_{21}\pmb{a1} & E_{21}\pmb{a2} & E_{21}\pmb{a3} & E_{21}\pmb{b}
\end{bmatrix}
$$

donde $\pmb{a}i$ es la columna $i$-ésima de $A$.

## Ejercicios

**Ejercicio 6:**

Cuáles tres matrices $E_{21}$, $E_{31}$ y $E_{32}$ hacen que $A$ se convierta en una matriz triangular superior $U$?

$
A=\begin{bmatrix}
1 & 1 & 0\\
4 & 6 & 1\\
-2 & 2 & 0
\end{bmatrix}\qquad$ y $\qquad E_{32}E_{31}E_{21}A=U$.

Multiplique las matrices $E$ para obtener una sola matriz $M$ tal que $MA=U$.

In [6]:
import numpy as np

A = np.matrix([[1,1,0], [4,6,1], [-2,2,0]])
E1 = np.matrix([[1,0,0], [-4,1,0], [0,0,1]])
E2 = np.matrix([[1,0,0], [0,1,0], [2,0,1]])
E3 = np.matrix([[1,0,0], [0,1,0], [0,-2,1]])
E3*E2*E1*A

matrix([[ 1,  1,  0],
        [ 0,  2,  1],
        [ 0,  0, -2]])

**Ejercicio 7:**

Multiplique las siguientes matrices:

$
\begin{bmatrix}
0 & 0 & 1\\
0 & 1 & 0\\
1 & 0 & 0
\end{bmatrix}\begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{bmatrix}\begin{bmatrix}
0 & 0 & 1\\
0 & 1 & 0\\
1 & 0 & 0
\end{bmatrix}\qquad\qquad\begin{bmatrix}
1 & 0 & 0\\
-1 & 1 & 0\\
-1 & 0 & 1
\end{bmatrix}\begin{bmatrix}
1 & 2 & 3\\
1 & 3 & 1\\
1 & 4 & 0
\end{bmatrix}$

**Ejercicio 8:**

Escriba los siguientes problemas mediante una forma matricial $A\pmb{x}=\pmb{b}$ y resuélvalos:

* $X$ tiene el doble de edad que $Y$ y sus edades suman 33.
* Los puntos $(2,5)$ y $(3,7)$ están sobre la misma linea $y=mx+c$. Encuentre $m$ y $c$.

**Ejercicio 9:**

Multiplique las siguientes matrices en el orden $EF$ y $FE$:

$$
E=\begin{bmatrix}
1 & 0 & 0\\
a & 1 & 0\\
b & 0 & 1
\end{bmatrix}\qquad\qquad F=\begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & c & 1
\end{bmatrix}
$$

Calcule también $E^2$, $F^3$. ¿Cuál es $F^{100}$?

**Ejercicio 10:**

Multiplique las siguientes matrices de permutación en los órdenes $PQ$ y $QP$ y también $P^2$:

$$
P=\begin{bmatrix}
0 & 1 & 0\\
1 & 0 & 0\\
0 & 0 & 1
\end{bmatrix}\qquad\qquad F=\begin{bmatrix}
0 & 0 & 1\\
0 & 1 & 0\\
1 & 0 & 0
\end{bmatrix}
$$

Encuentre una matriz $M$ no diagonal cuyo cuadrado sea $M^2=I$.

## Revisión de las ideas principales

* La matriz identidad consiste en unos en la diagonal y ceros en el resto de posiciones.

* La matriz de eliminación $E_{ij}$ se obtiene al cambiar la posición $i,j$ por $-\ell_{ij}$ en la matriz identidad.

* Multiplicar el sistema $A\pmb{x}=\pmb{b}$ por $E_{21}$ sustrae el múltiplo $\ell_{21}$ de la ecuación 1 en la ecuación 2. 

* La matriz permutación $P_{ij}$ se obtiene al intercambiar las filas $i$ y $j$ en la matriz identidad.

* Para la matriz aumentada $\begin{bmatrix}
A & \pmb{b}\end{bmatrix}$ el paso de eliminación que acabamos de mencionar proporciona $\begin{bmatrix}
E_{21}A & E_{21}\pmb{b}\end{bmatrix}$.

* Cuando una matriz $A$ multiplica una matriz $B$, la multiplica por cada columna de $B$ separadamente:

$$
\begin{bmatrix}
A(\mbox{columna 1 de $B$}) & A(\mbox{columna 2 de $B$}) & A(\mbox{columna 3 de $B$})
\end{bmatrix}
$$


## Referencias

- Strang, Gilbert (2009) *Introduction to Linear Algebra*, 4th Edition. Wellesley-Cambridge Press, 2009.
